#ifndef __CHINESE_CODE_H
#define __CHINESE_CODE_H

#include "stm32f10x.h"
#include "lcd.h"
/*
extern uchar const Chinese_text_16x16[];
extern uchar const Chinese_code_16x16[];

extern uchar const Chinese_text_16x8[];
extern uchar const Chinese_code_16x8[];

extern unsigned char const dis_code[];
extern unsigned char const PWM1[];
extern unsigned char const PWM_16[];

extern unsigned char const P_16[];
extern unsigned char const W_16[];
extern unsigned char const M_16[];

extern unsigned char const Number[10][16];
extern unsigned char const colon[];
extern unsigned char const H[];
extern unsigned char const Z[];
extern unsigned char const Percent[];
extern unsigned char const Zero_Clear[];

extern uchar const jing2[];
extern uchar const lian2[];
extern uchar const xun2[];
extern uchar const dian2[];
extern uchar const zi2[];
extern uchar const bmp1[];
extern uchar const bmp2[];
extern uchar const bmp3[];
extern uchar const bmp4[];
extern uchar const bmp5[];
extern uchar const bmp6[];
extern uchar const bmp7[];
extern uchar const bmp8[];
extern uchar const bmp9[];
*/
#endif




